// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sflysnodxcufeszuymxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbHlzbm9keGN1ZmVzenV5bXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODc4MjQsImV4cCI6MjA1MzY2MzgyNH0.c8MMJ3WkH_EE1YSkJIfANZk9TA9rxh8P5BNE9LBq8uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);